# Usa una imagen base de OpenJDK para Java 11
FROM openjdk:11

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/ms-transaction-auditoria

# Copia el archivo JAR de la aplicación al directorio de trabajo
COPY target/ms-auditoria-0.0.1-SNAPSHOT.jar auditoria.jar

# Comando para iniciar la aplicación
ENTRYPOINT  ["java", "-jar", "auditoria.jar"]